import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import Header from '@/components/layouts/Header'
import Footer from '@/components/layouts/Footer'
import { NextAuthProvider } from '@/lib/next-auth/provider'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
    title: 'local Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
            <body
                className={`${notoSansJP.className} flex flex-col min-h-screen`}
            >
                <NextAuthProvider>
                    <Header />
                    <div className="flex-grow">{children}</div>
                    <Footer />
                </NextAuthProvider>
            </body>
        </html>
    )
}
